url: https://tmerlier.github.io
baseurl:

# Site settings
title: Team Devils
email: teamdevils@gmail.fr
description: "Site officiel de la Team Devils"

# Collections
collections:
  members:
    title: Members
    output: true
    permalink: /members/:path/
  sponsors:
    title: Sponsors
    output: true
    permalink: /sponsors/:path/

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      pic: default.png

prizes:
  - year: 2013
    name: OPEN BULLDOGG
    ranking: 3ème et 6ème
    record: true
  - year: 2014
    name: OPEN NO LIMIT
    ranking: 3ème
    record: true
  - year: 2014
    name: NORMANDIE PAINTBALL LIGUE
    ranking: 8ème
    record: false
  - year: 2015
    name: Trophée TOXIC
    ranking: 8ème de la poule et 25ème place
    record: false
  - year: 2015
    name: NORMANDIE PAINTBALL LIGUE
    ranking: 7ème place
    record: false
  - year: 2016
    name: Trophée TOXIC
    ranking: 9ème de la poule et 20ème place
    record: false
  - year: 2017
    name: Trophée TOXIC
    ranking: 4ème et 6ème de la poule amateur
    record: true
  - year: 2017
    name: CHAMPIONS PAINTBALL SERIES
    ranking: 8ème
    record: false

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Impasse des clos
  - line: 27000 Évreux

# Build settings
markdown: kramdown
permalink: pretty